on:
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '0 15 * * *'

name: docs

jobs:
  R-CMD:
    if: (github.actor == 'henry090')
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest }

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          Rscript -e "install.packages('pkgdown')"

      - name: Install MacOS/Windows/Linux
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies =  TRUE)"
          Rscript -e "remotes::install_cran('rcmdcheck')"

      - name: Install Python
        run: |
          Rscript -e "remotes::install_github('rstudio/reticulate')"
          Rscript -e "try(reticulate::install_miniconda())"
      - name: Install FASTAI & TORCH
        run: |
          Rscript -e "reticulate::conda_create('r-reticulate', packages = c('python==3.6.9'))"
          Rscript -e "reticulate::conda_install('r-reticulate','IPython')"
          Rscript -e "reticulate::py_install('torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html',pip = TRUE)"
          Rscript -e "reticulate::py_install('fastai',pip = TRUE)"
          Rscript -e "reticulate::py_install('pydicom kornia opencv-python scikit-image',pip = TRUE)"
          Rscript -e "reticulate::py_module_available('IPython')"
          Rscript -e "remotes::install_github('henry090/fastai', INSTALL_opts=c('--no-multiarch'))"

      - name: Render site
        run: |
          Rscript -e "pkgdown::build_site()"
      - name: Commit files
        run: |
          git config --global user.email ${{ github.EMAIL }}
          git config --global user.name ${{ github.actor }}
          git add ./docs
          git commit -m "docs are updated"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
